version: '3'

services:
  database:
    image: mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/
    networks:
      - symfony
    depends_on:
      - database
    links:
      - redis
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
    ports:
      - 8080:8080
    networks:
      - symfony
  redis:
    image: redis
    expose:
      - "6379"
    networks:
      - symfony

networks:
  symfony: